import { AXLES,CABS,CRAWLER_SPEC,FINISHES,SOURCES,engineFor,type TruckConfig } from '../data/catalog';
export type SelectedPart='engine'|'gear'|'cab'|'axle'|'mirror'|'lights'|'interior'|'paint';
export type PartInfo={title:string;description:string;facts:[string,string][];source:string;note?:string};
const rpm={D17A600:{power:'1.500–1.700',torque:'900–1.400'},D17A700:{power:'1.600–1.700',torque:'950–1.400'},D17A780:{power:'1.700',torque:'1.000–1.200'}};
const gearboxCapacity={ATO3112:3150,ATO3512:3550,ATO3812:3800};
export function selectedPartInfo(part:SelectedPart,truck:TruckConfig):PartInfo{
  const engine=engineFor(truck),range=rpm[engine.id],source=SOURCES.specifications;
  if(part==='engine')return {title:engine.name+' hk',description:'D17 er Volvos 17,3-liters sekscylindrede motor til tung transport.',facts:[['Maks. effekt',`${engine.kw} kW ved ${range.power} o/min`],['Maks. moment',`${engine.torque.toLocaleString('da-DK')} Nm ved ${range.torque} o/min`],['Geartilpasning',engine.gearbox]],source,note:engine.id==='D17A700'?'700 hk kan også leveres i en variant til B100 biodiesel.':undefined};
  if(part==='gear')return {title:'I-Shift · '+engine.gearbox,description:truck.crawler?'Krybegear giver mulighed for præcis manøvrering ved meget lav hastighed.':'Automatisk split- og rangegearkasse med overgear.',facts:truck.crawler?[['Gear','12 normale + 1 krybegear'],['Variant',CRAWLER_SPEC.code],['Krybeudveksling',CRAWLER_SPEC.ratio.toString().replace('.',',')+':1'],['Ekstra vægt',CRAWLER_SPEC.addedMass+' kg']]:[['Fremadgående gear','12'],['Maks. motormoment',gearboxCapacity[engine.gearbox].toLocaleString('da-DK')+' Nm'],['Højeste gear','Overgear']],source};
  if(part==='cab'){
    const cab=CABS.find(c=>c.id===truck.cab)!;
    return {title:cab.name,description:truck.cab==='FH16AXHE'?'XXL har en forlænget sovekabine og en bredere, længere underkøje.':truck.cab==='FH16ALSL'?'Det lave tag giver en mindre udvendig højde.':truck.cab==='FH16AXHS'?'Ekstra højt førerhus med mere plads og opbevaring.':truck.cab==='FH16AHSL'?'Et højt langt førerhus med ståplads over motortunnellen.':'Langt førerhus med soveplads og en lavere indvendig højde.',facts:[['Volvo-kode',cab.id],['Indvendig højde',cab.height+' cm'],['Over motortunnel',cab.tunnelHeight+' cm'],...(truck.cab==='FH16AXHE'?[['Underkøjens længde','213 cm'] as [string,string]]:[])],source:truck.cab==='FH16AXHE'?SOURCES.cabXXL:truck.cab==='FH16AXHS'?SOURCES.cabXL:source};
  }
  if(part==='axle'){const axle=AXLES.find(a=>a.id===truck.axle)!;return {title:axle.name,description:truck.axle==='6x4'?'Tandemtrækker med to drivaksler til tunge transportopgaver.':'Trækker med én drivaksel og to aksler i alt.',facts:[['Chassis','Trækker'],['Aksler',truck.axle==='6x4'?'3 aksler / 2 drivaksler':'2 aksler / 1 drivaksel'],['Chassishøjde',truck.axle==='6x4'?'High':'Medium']],source:SOURCES.overview};}
  if(part==='mirror')return {title:truck.cms?'Camera Monitor System':'Traditionelle sidespejle',description:truck.cms?'Kameramonitorer giver udvidet udsyn og reducerer luftmodstanden.':'Volvo FH16 Aero kan også vælges med traditionelle sidespejle.',facts:truck.cms?[['Udsyn','Bredere synsfelt'],['Volvo-funktioner','Night Vision og parkeringsovervågning']]:[['Udstyr','Mirrors'],['Model','FH16 Aero']],source:'https://www.volvotrucks.dk/da-dk/trucks/models/volvo-fh16-aero.html',note:truck.cms?'Spillet viser kamerafeeds; Volvos særlige overvågningsfunktioner er ikke simuleret.':undefined};
  if(part==='lights')return {title:truck.adaptiveLights?'LED med adaptivt fjernlys':'LED-forlygter',description:truck.adaptiveLights?'Fjernlysets segmenter tilpasses trafikken for at bevare udsynet og begrænse blænding.':'Volvos LED-forlygter er basisvalget i den viste konfiguration.',facts:[['Volvo-variant',truck.adaptiveLights?'HL-LED3':'HL-LED'],['Natkørsel','Automatiske forlygter i spillet']],source:SOURCES.specification,note:truck.adaptiveLights?'Den trafikafhængige segmentstyring er ikke simuleret i prototypen.':undefined};
  if(part==='interior')return {title:truck.blackEdition?'Black Edition':'FH16-interiør',description:truck.blackEdition?'Volvo-mærket sort læder på stolebetræk og dørpaneler.':'FH16-interiøret bruger læder og nuancer af Coral og Raven.',facts:truck.blackEdition?[['Materiale','Sort læder'],['Pakkens dele','Stolebetræk og dørpaneler']]:[['Materiale','Læder'],['Farvetoner','Coral / Raven']],source:truck.blackEdition?SOURCES.blackEdition:source};
  const color=FINISHES.find(c=>c.id===truck.color)!;return {title:color.name,description:'Et metallic-lakvalg fra Volvos Truck Builder.',facts:[['Farvekode',color.id],['Finish','Metallic']],source:SOURCES.builder};
}
